export const STATE_REDUCER_KEY = 'enrollment';

export const ROUTE_KEYS = {
    ENROLLMENT: 'Enrollment',
    ENROLLMENTINPROGRESS: 'EntrollmentInProgress',
    ENROLLMENTSUBSCRIPTION: 'EnrollmentSubscription',
    ENROLLMENTSUBSCRIBED: 'EnrollmentSubscribed',
    ENROLLMENTQRCODE: 'EnrollmentQrCode',
};

export const LIST_VIEW_KEYS = {
    ENROLLMENT_CUSTOMER_PROPERTY_TENANT_NAME: 'CUSTOMER_PROPERTY_TENANT_NAME',
    ENROLLMENT_CUSTOMER_WARD: 'CUSTOMER_WARD',
    ENROLLMENT_CUSTOMER_PROPERTY_NUMBER: 'CUSTOMER_PROPERTY_NUMBER',
    ENROLLMENT_CUSTOMER_PROPERTY_OWNER_NAME: 'CUSTOMER_PROPERTY_OWNER_NAME',
    ENROLLMENT_CUSTOMER_TERRACE_FARM_STATUS: 'CUSTOMER_TERRACE_FARM_STATUS',
    ENROLLMENT_CUSTOMER_DOOR_STATUS: 'CUSTOMER_DOOR_STATUS',
    ENROLLMENT_CUSTOMER_PROPERTY_TENANT_PHONE_NUMBER: 'CUSTOMER_PROPERTY_TENANT_PHONE_NUMBER',
    ENROLLMENT_CUSTOMER_ASSOCIATION_NAME: 'CUSTOMER_ASSOCIATION_NAME',
    ENROLLMENT_CUSTOMER_BIO_WASTE_STATUS: 'CUSTOMER_BIO_WASTE_STATUS',
    ENROLLMENT_CUSTOMER_GREEN_PROTOCOL_STATUS: 'CUSTOMER_GREEN_PROTOCOL_STATUS',
    ENROLLMENT_CUSTOMER_NON_BIO_WASTE_STATUS: 'CUSTOMER_NON_BIO_WASTE_STATUS',
    ENROLLMENT_CUSTOMER_PROPERTY_NAME: 'CUSTOMER_PROPERTY_NAME',
    ENROLLMENT_CUSTOMER_PROPERTY_OWNER_PHONE_NUMBER: 'CUSTOMER_PROPERTY_OWNER_PHONE_NUMBER',
    ENROLLMENT_CUSTOMER_PROPERTY_TYPE: 'CUSTOMER_PROPERTY_TYPE',
    ENROLLMENT_CUSTOMER_TOTAL_HOUSE: 'CUSTOMER_TOTAL_HOUSE',
    ENROLLMENT_CUSTOMER_TRADING_TYPE: 'CUSTOMER_TRADING_TYPE',
    ENROLLMENT_CUSTOMER_ADDRESS: 'CUSTOMER_ADDRESS',
    ENROLLMENT_CUSTOMER_LOCATION: 'CUSTOMER_LOCATION',
    ENROLLMENT_CUSTOMER_IMAGE: 'CUSTOMER_IMAGE',
    SURVEYOR: 'SURVEYOR',
    SURVEY_DATE: 'SURVEY_DATE',
    CUSTOMER_NUMBER: 'CUSTOMER_NUMBER',
    DISTRICT: 'DISTRICT',
    ORGANIZATION: 'ORGANIZATION',
    SERVICE_WORKER: 'SERVICE_WORKER',
    QR_CODE: 'QR_CODE',
    SERVICE_WASTE_WEIGHT: 'WASTE_WEIGHT',
    SERVICE_WASTE_QUALITY: 'WASTE_QUALITY'
};

export const CUSTOMER_ENROLLMNET_UI_KEYS = {
    ENROLLMENT_CUSTOMER_PROPERTY_TENANT_NAME: 'CUSTOMER_PROPERTY_TENANT_NAME',
    ENROLLMENT_CUSTOMER_WARD: 'CUSTOMER_WARD',
    ENROLLMENT_CUSTOMER_PROPERTY_NUMBER: 'CUSTOMER_PROPERTY_NUMBER',
    ENROLLMENT_CUSTOMER_PROPERTY_OWNER_NAME: 'CUSTOMER_PROPERTY_OWNER_NAME',
    ENROLLMENT_CUSTOMER_TERRACE_FARM_STATUS: 'CUSTOMER_TERRACE_FARM_STATUS',
    ENROLLMENT_CUSTOMER_DOOR_STATUS: 'CUSTOMER_DOOR_STATUS',
    ENROLLMENT_CUSTOMER_PROPERTY_TENANT_PHONE_NUMBER: 'CUSTOMER_PROPERTY_TENANT_PHONE_NUMBER',
    ENROLLMENT_CUSTOMER_ASSOCIATION_NAME: 'CUSTOMER_ASSOCIATION_NAME',
    ENROLLMENT_CUSTOMER_BIO_WASTE_STATUS: 'CUSTOMER_BIO_WASTE_STATUS',
    ENROLLMENT_CUSTOMER_GREEN_PROTOCOL_STATUS: 'CUSTOMER_GREEN_PROTOCOL_STATUS',
    ENROLLMENT_CUSTOMER_NON_BIO_WASTE_STATUS: 'CUSTOMER_NON_BIO_WASTE_STATUS',
    ENROLLMENT_CUSTOMER_PROPERTY_NAME: 'CUSTOMER_PROPERTY_NAME',
    ENROLLMENT_CUSTOMER_PROPERTY_OWNER_PHONE_NUMBER: 'CUSTOMER_PROPERTY_OWNER_PHONE_NUMBER',
    ENROLLMENT_CUSTOMER_PROPERTY_TYPE: 'CUSTOMER_PROPERTY_TYPE',
    ENROLLMENT_CUSTOMER_TOTAL_HOUSE: 'CUSTOMER_TOTAL_HOUSE',
    ENROLLMENT_CUSTOMER_TRADING_TYPE: 'CUSTOMER_TRADING_TYPE',
    ENROLLMENT_CUSTOMER_ADDRESS: 'CUSTOMER_ADDRESS',
    ENROLLMENT_CUSTOMER_LOCATION: 'CUSTOMER_LOCATION',
    ENROLLMENT_CUSTOMER_IMAGE: 'CUSTOMER_IMAGE',
    SURVEYOR: 'SURVEYOR',
    SURVEY_DATE: 'SURVEY_DATE',
    CUSTOMER_NUMBER: 'CUSTOMER_NUMBER',
    DISTRICT: 'DISTRICT',
    ORGANIZATION: 'ORGANIZATION',
    QR_CODE: 'QR_CODE',
    SERVICE_COMPLETION_DATE: 'SERVICE_COMPLETION_DATE',
    SERVICE: 'SERVICE'
};

export const SERVICE_EXECUTION_UI_KEYS = {
    ENROLLMENT_CUSTOMER_WARD: 'CUSTOMER_WARD',
    ENROLLMENT_CUSTOMER_DOOR_STATUS: 'CUSTOMER_DOOR_STATUS',
    ENROLLMENT_CUSTOMER_PROPERTY_NAME: 'CUSTOMER_PROPERTY_NAME',
    CUSTOMER_NUMBER: 'CUSTOMER_NUMBER',
    SERVICE: 'SERVICE',
    SERVICE_WORKER: 'SERVICE_WORKER',
    SERVICE_WASTE_WEIGHT: 'WASTE_WEIGHT',
    SERVICE_WASTE_QUALITY: 'WASTE_QUALITY',
    SERVICE_COMPLETION_DATE: 'SERVICE_COMPLETION_DATE'
};

export const CUSTOMER_ENROLLMENT_LIST_VIEW_KEYS = {
    ENROLLMENT_CUSTOMER_WARD: 'CUSTOMER_WARD',
    ENROLLMENT_CUSTOMER_PROPERTY_TENANT_PHONE_NUMBER: 'CUSTOMER_PROPERTY_TENANT_PHONE_NUMBER',
    ENROLLMENT_CUSTOMER_PROPERTY_OWNER_PHONE_NUMBER: 'CUSTOMER_PROPERTY_OWNER_PHONE_NUMBER',
    ENROLLMENT_CUSTOMER_PROPERTY_NAME: 'CUSTOMER_PROPERTY_NAME',
    ENROLLMENT_CUSTOMER_IMAGE: 'CUSTOMER_IMAGE',
    CUSTOMER_NUMBER: 'CUSTOMER_NUMBER',
    SURVEYOR: 'SURVEYOR',
    ENROLLMENT_CUSTOMER_DOOR_STATUS: 'CUSTOMER_DOOR_STATUS'
};

export const SERVICE_EXECUTION_LIST_VIEW_KEYS = {
    ENROLLMENT_CUSTOMER_WARD: 'CUSTOMER_WARD',
    ENROLLMENT_CUSTOMER_PROPERTY_NAME: 'CUSTOMER_PROPERTY_NAME',
    SERVICE: 'SERVICE',
    SERVICE_WORKER: 'SERVICE_WORKER',
    CUSTOMER_NUMBER: 'CUSTOMER_NUMBER',
    ENROLLMENT_CUSTOMER_DOOR_STATUS: 'CUSTOMER_DOOR_STATUS',
    SERVICE_COMPLETION_DATE: 'SERVICE_COMPLETION_DATE'
};

export const CUSTOMER_SERVICE_EXECUTION_LIST_VIEW_KEYS = {
    SERVICE: 'SERVICE',
    SERVICE_WORKER: 'SERVICE_WORKER',
    SERVICE_COMPLETION_DATE: 'SERVICE_COMPLETION_DATE',
    ENROLLMENT_CUSTOMER_DOOR_STATUS: 'CUSTOMER_DOOR_STATUS'
};
